### ISSUE TITLE
Plagiarism Check

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/feedbacksystem#14]
We need tools that helps us to detect plagiarism among the submissions / solutions.

**Comment by bees4ever** [comment]
- [ ] enable in submissioncheck to send and answer `plagiarismchecker`
- [ ] plagiarismchecker must can download all submissions from a course (into filesystem)
- [ ] maybe also delete unused ones
- [ ] DB: Task -> plagiat check done (boolean), for each submission: Plagiat passed: NULL, TRUE, FALSE
- [ ] add testsystem "plagiarismchecker" (there can be later also node included)
- [ ] Threat in WS to send plagiarism
- [ ] Docent should somehow upload a script
