### ISSUE TITLE
Projekt Module for Plagiarism Checker

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/feedbacksystem#21]
Add a project module for the plagiarism checker.

**Comment by bees4ever** [comment]
ToDo:

- [] Upload Script Web Gui
- [] Upload Script `Secrettokenchecker`
- [] Use script in execution
- [] Feedback for docent when plagiat check is ready

**Comment by andrej-sajenko** [comment]
Simple Plagiarism Check was implemented in #270
