### ISSUE TITLE
[Ticket#14687043] Ticket CAS Login Feedbacksystem

### ISSUE THREAD

**Issue by bees4ever** [thm-mni-ii/feedbacksystem#296]
aus Datenschutzgründen werden nur begrenzt Attribute an Clients gesendet, die nicht bei uns registriert sind. Wenn Sie ein THM-Internes System betreiben, kann ich die Quelle des Logins gerne bei uns registrieren. Sie sollten dann alle nötigen CAS-Attribute erhalten und eine weitere LDAP-Anfrage erübrigt sich dann. Details zum Vorgehen undauslesen der Attribute finden Sie auf der Webseite von Apareo-Cas.

**Comment by andrej-sajenko** [comment]
External users get a local account.
