### ISSUE TITLE
Display course progress

### ISSUE THREAD

**Issue by andrej-sajenko** [thm-mni-ii/feedbacksystem#376]
In the course list view, display for each course how many tasks are solved correctly and the total number of tasks.
Something like 5/8.

**Comment by snicki13** [comment]
Maybe give an option to define "optional tasks"

**Comment by Medienkunzt** [comment]
@TimonPllkrn which option do you prefer?
![Image](https://user-images.githubusercontent.com/57532417/190638581-beed213d-2bdc-4622-b709-bd3b90346db7.png)

**Comment by TimonPllkrn** [comment]
> @TimonPllkrn which option do you prefer? 

I prefer the first solution. But I would also add a tooltip which opens on hover like the following example:
![grafik](https://user-images.githubusercontent.com/64217916/191202450-1cbb2972-f727-4ce9-a456-65472d007a67.png)

**Comment by Medienkunzt** [comment]
> > @TimonPllkrn which option do you prefer?
> 
> I prefer the first solution. But I would also add a tooltip which opens on hover like the following example: ![grafik](https://user-images.githubusercontent.com/64217916/191202450-1cbb2972-f727-4ce9-a456-65472d007a67.png)

This is a very good idea. We should include more info dialogs anyway.
