### ISSUE TITLE
Upload of Checker Configuration files

### ISSUE THREAD

**Issue by hwng38** [thm-mni-ii/feedbacksystem#428]
The upload of Checker Configuration files is faulty on the server side and needs to be fixed.
Currently only one file per Checker is possible.

**Comment by andrej-sajenko** [comment]
After 017f29bc25c92d7c15d0bc6b21f3362b1f275c8b and e96c05b7d180eda657a9df775152cda2133fa52f 
both files should be stored correctly.
On the server side the update of the flag that indicates if a file was uploaded was done incorrectly.
The update of one flag did update the flag of the second file too. We had a dirty read, if both files are updated nearly simultaneously.
