### ISSUE TITLE
Task configuration error

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#441]
It is not possible to upload only one file for the Cheker configuration (Which should be possible for the Bash Checker), because you will get an error message that all fields must be filled in.

![grafik](https://user-images.githubusercontent.com/63304184/96591310-69ff0c80-12e7-11eb-8a20-fd2289369b05.png)

**Comment by andrej-sajenko** [comment]
fixed: e185ce25c1bb48ed3a829f045ce402caaeb9fc69
