### ISSUE TITLE
Error while deleting

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#442]
- [ ] If you try to delete a course nothing happens
- [x] If you try to delete a task that you have passed, the following error will occur:
![grafik](https://user-images.githubusercontent.com/63304184/96599205-f8778c00-12ef-11eb-9695-43e03d6256aa.png)
- [x] If you try to delete a (Runner- ) configuration from a task you have passed the following error will occur:
![grafik](https://user-images.githubusercontent.com/63304184/96599522-4f7d6100-12f0-11eb-9212-ec5a406a6962.png)

**Comment by andrej-sajenko** [comment]
We need a clean delete of a course to avoid data zombies.
My suggestion is that wherever we delete a
- task, we delete every configuration und submission made for that task (including uploaded data and results)
- course, we delete every task and every registration made for that course

After that the the constraint should not be violated anymore.

**Comment by mxsph** [comment]
> We need a clean delete of a course to avoid data zombies.
> My suggestion is that wherever we delete a
> 
>     * task, we delete every configuration und submission made for that task (including uploaded data and results)
> 
>     * course, we delete every task and every registration made for that course
> 
> 
> After that the constraint should not be violated anymore.

Yes that would be a good solution to the problem :+1:
