### ISSUE TITLE
User role is not saved

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/feedbacksystem#449]
When I change the role of a user in /courses/id/participants, the changed role is not saved and reset upon reload.

**Comment by snicki13** [comment]
I am "Dozent" and trying to change "Student" to "Tutor"

**Comment by punchparty93** [comment]
In the current version there is a bug displaying the wrong role for online users. Was the elevated account able to do privileged actions ?

**Comment by andrej-sajenko** [comment]
fixed in 8699a5637084a470504e7da021a4b19be352cda1
