### ISSUE TITLE
getAllSubmissions throws 500

### ISSUE THREAD

**Issue by hwng38** [thm-mni-ii/feedbacksystem#473]
The getAllSubmissions route throws a 500 error.

The response is:
{
    "timestamp": 1604951868596,
    "status": 500,
    "error": "Internal Server Error",
    "message": "PreparedStatementCallback; bad SQL grammar [SELECT submission_id, submission_time, configuration_id, exit_code, result_text, checker_type, ext_info FROM user_task_submission JOIN task USING(task_id) LEFT JOIN checker_result using (submission_id) LEFT JOIN checkrunner_configuration using (configuration_id) WHERE user_id = ? AND course_id = ? AND user_task_submission.task_id = ?]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'ext_info' in 'field list'",
    "path": "/api/v1/users/863/courses/155/tasks/375/submissions"
}

**Comment by mxsph** [comment]
Yes, this is because the database schema has changed (to store the new information). 
To adjust your database you can use the command: `ALTER TABLE fbs.checker_result ADD COLUMN ext_info JSON AFTER result_text;`
