### ISSUE TITLE
FBA: Link to participate anonymous surveys

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/feedbacksystem#530]
Afaik it is only possible to enter a survey, even anonymously, after logging in to the FBS, going to the FBA and entering the session id. 
Is it possible to create a "session link" - atleast for anonymous surveys - to directly participate without going through this whole process?

**Comment by mxsph** [comment]
The issue was moved to the FBA repo (https://git.thm.de/swtp-feedback-app/frontend/-/issues/7)
