### ISSUE TITLE
Chrome: Participant list jumping

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/feedbacksystem#534]
The participant list of the digital classroom jumps in chrome browser. Firefox does not seem to be affected.

**Comment by snicki13** [comment]
No network communication, so this seems to happen just in JS / CSS.

**Comment by snicki13** [comment]
The lis tis refreshed and reordered about every second even with unchanged participants. The list switches between two sort orders.

**Comment by snicki13** [comment]
@kimiannalena I have no idea how to fix this :(

**Comment by kimiannalena** [comment]
I will look into this later today, already have an idea!

**Comment by mxsph** [comment]
#535 is only a Temporary solution and the problem should be fixed properly
