### ISSUE TITLE
[Web] Add semester field to courses and auto archive old courses

### ISSUE THREAD

**Issue by Zitrone44** [thm-mni-ii/feedbacksystem#610]
---

needs #701

**Comment by Medienkunzt** [comment]
Please describe the requirements in more detail. I have tried to implement the issue title. In the process I have encountered more and more questions:
Are semesters created automatically?
Who is allowed to create semesters?
How do we define a semester from the period? (start and end dates are missing in the model)
Where should archived courses be displayed?
...
This ticket seems more extensive than it is presented. Please define what should be implemented here
