### ISSUE TITLE
Improvement of the SQL-Checker

### ISSUE THREAD

**Issue by Jonas960** [thm-mni-ii/feedbacksystem#730]
- [x] Add Packagemanger for Dependencies (https://python-poetry.org/)
- [x] Add formatting tool (https://deepsource.io/blog/python-code-formatters/)
- [x] Add Linting Tools (https://github.com/PyCQA/pylint)
- [x] CI/CD: Build + possible testcases (@mxsph)
- [x] CI/CD: Publish dockerimages to Dockerhub (@mxsph)

**Comment by Medienkunzt** [comment]
- [ ] Refactor Code for PyLint-Style
