### ISSUE TITLE
No loading bar is displayed during a file upload for a submission

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#750]
**Describe the bug**
When uploading a larger file, the loading indicator is only displayed after the file has been uploaded, which leads to the student assuming that nothing has happened and possibly trying to upload the file again

**To Reproduce**
1. Create a Task with the media type File
2. Upload a larger file
3. See error

**Expected behavior**
The loading indicator should be displayed immediately after clicking on the 'Submit' button.

**Screenshots**

![error](https://user-images.githubusercontent.com/63304184/189608059-fbdb7e23-ff9b-435a-81fe-4f486609e334.gif)

**Comment by nicosoethe** [comment]
I tried to reproduce the behavior but it worked fine for me. What was the size of your file?

**Comment by mxsph** [comment]
The file I tested with was `33kiB` in size. If you tested the upload locally, it is possible that the error does not occur because there is no delay due to the internet connection. To test the upload locally you can set a throttling in the dev-tools of your browser.
