### ISSUE TITLE
add result table for SQL Playground

### ISSUE THREAD

**Issue by TimonPllkrn** [thm-mni-ii/feedbacksystem#780]
- [x] use existing result table and add to result container
- [x] (fit table to 10 entries)
- [x] add pagination for table (could use material ui angular)
- [x] download table content source json
- [x] make table x-scrollable if content overflows

![grafik](https://user-images.githubusercontent.com/64217916/192501328-e83cbcdc-b704-4d7c-ac8c-265efcfe25a3.png)

**Comment by Medienkunzt** [comment]
Sample JSON:

[mediumTable.txt](https://github.com/thm-mni-ii/feedbacksystem/files/9724015/mediumTable.txt)
[smallTable.txt](https://github.com/thm-mni-ii/feedbacksystem/files/9724017/smallTable.txt)
[largeTable.txt](https://github.com/thm-mni-ii/feedbacksystem/files/9724016/largeTable.txt)
