### ISSUE TITLE
Update REST Tasks after Meeting 10/12

### ISSUE THREAD

**Issue by bees4ever** [thm-mni-ii/feedbacksystem#90]
- [x] get all results for a course for a user 
- [x] Add a deadline for a task 
- [x] task/submission service -> (Outer join!) for every course user get also info if nothing was submitted
-----------Questions--------------
- [ ] maybe extra route to get only those who do not have any submissions.
- [ ] limit submissions? -> extra field per task

**Comment by andrej-sajenko** [comment]
Only optional improvements open.
