### ISSUE TITLE
Button to move on to the next task

### ISSUE THREAD

**Issue by Medienkunzt** [thm-mni-ii/feedbacksystem#923]
Currently, it is very frustrating to navigate through a whole series of tasks.
If you have solved a task correctly, then you have to navigate back to find the new task and click on it.
This should be improved by being able to switch to the next or previous task within the task.
Also, there should be a function to go to the next or previous unsolved task
If there should be no previous or last task, then the buttons should be disabled

![image](https://user-images.githubusercontent.com/57532417/200308321-89d3b2b4-ec87-4f45-bce8-521a7b4323e5.png)
![image](https://user-images.githubusercontent.com/57532417/200308404-ee6c634e-6c86-42f8-93a6-9931a6c9cfe8.png)

**Comment by mxsph** [comment]
I think this is a very good idea, but I would probably place the buttons a little differently, as they are currently a little too prominent. I think it would be better if they were placed in the header? (@Medienkunzt, @TimonPllkrn)

![grafik](https://user-images.githubusercontent.com/63304184/200373542-2facd61d-db1f-48d6-9143-8c636707e7f4.png)

**Comment by Medienkunzt** [comment]
@mxsph I agree with the prominence aspect, but I don't like the integration in the header. We have a float left and a float right. 
If you insert something in the middle, it will always look asymmetrical and skewed. Moreover, the meaning of the back button on the left could be misunderstood.

My suggestion would be to use only the icons without the colored containers,
or to place the buttons between header and the submission-component.
But with the second option we have again the problem with the misunderstanding.
